--create database
DROP DATABASE IF EXISTS webapp;
CREATE DATABASE IF NOT EXISTS webapp;
USE webapp;

--CREATE TABLE

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS USERS(
    userid bigint(11) NOT NULL AUTO INCREMENT,
    FULLNAME VARCHAR(50) NOT NULL DEFAULT '',
    FULLNAME VARCHAR(50) NOT NULL DEFAULT '',
    FULLNAME VARCHAR(50) NOT NULL DEFAULT '',
    FULLNAME VARCHAR(50) NOT NULL DEFAULT '',
    FULLNAME VARCHAR(50) NOT NULL DEFAULT '',
)
)
)
)
)
)
