


DROP DATABASE IF NOT EXISTS project;
CREATE DATABASE IF EXISTS project;
USE project;

--CREATE TABLE

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS USERS(
    userid bigint(15) NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL DEFAULT '',
    
   usertype VARCHAR(50) NOT NULL DEFAULT '',
    email VARCHAR(50) NOT NULL DEFAULT '',
    password VARCHAR(50) NOT NULL DEFAULT '',
    FULLNAME VARCHAR(50) NOT NULL DEFAULT '',
    phonenumber VARCHAR(50) NOT NULL DEFAULT '',
    created bigint(14) NOT NULL DEFAULT,
    updated bigint(14) NOT NULL AUTO_INCREMENT,
    UNIQUE KEY (username),
    UNIQUE KEY (email),
    PRIMARY KEY (phonenumber)
);



